/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * The version of the OpenAPI document: v2
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AddEnvironmentVariableToContext200Response {
    /// The name of the environment variable
    #[serde(rename = "variable")]
    pub variable: String,
    /// The date and time the environment variable was created.
    #[serde(rename = "created_at")]
    pub created_at: String,
    /// The date and time the environment variable was updated
    #[serde(rename = "updated_at")]
    pub updated_at: String,
    /// ID of the context (UUID)
    #[serde(rename = "context_id")]
    pub context_id: uuid::Uuid,
    /// A human-readable message
    #[serde(rename = "message")]
    pub message: String,
}

impl AddEnvironmentVariableToContext200Response {
    pub fn new(
        variable: String,
        created_at: String,
        updated_at: String,
        context_id: uuid::Uuid,
        message: String,
    ) -> AddEnvironmentVariableToContext200Response {
        AddEnvironmentVariableToContext200Response {
            variable,
            created_at,
            updated_at,
            context_id,
            message,
        }
    }
}
