/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * The version of the OpenAPI document: v2
 *
 * Generated by: https://openapi-generator.tech
 */

/// Artifact : An artifact

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Artifact {
    /// The artifact path.
    #[serde(rename = "path")]
    pub path: String,
    /// The index of the node that stored the artifact.
    #[serde(rename = "node_index")]
    pub node_index: i64,
    /// The URL to download the artifact contents.
    #[serde(rename = "url")]
    pub url: String,
}

impl Artifact {
    /// An artifact
    pub fn new(path: String, node_index: i64, url: String) -> Artifact {
        Artifact {
            path,
            node_index,
            url,
        }
    }
}
