/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * The version of the OpenAPI document: v2
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BundleDiff {
    #[serde(rename = "created", skip_serializing_if = "Option::is_none")]
    pub created: Option<Vec<String>>,
    #[serde(rename = "deleted", skip_serializing_if = "Option::is_none")]
    pub deleted: Option<Vec<String>>,
    #[serde(rename = "modified", skip_serializing_if = "Option::is_none")]
    pub modified: Option<Vec<String>>,
}

impl BundleDiff {
    pub fn new() -> BundleDiff {
        BundleDiff {
            created: None,
            deleted: None,
            modified: None,
        }
    }
}
