/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * The version of the OpenAPI document: v2
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BundlePayload {
    #[serde(rename = "policies", skip_serializing_if = "Option::is_none")]
    pub policies: Option<::std::collections::HashMap<String, String>>,
}

impl BundlePayload {
    pub fn new() -> BundlePayload {
        BundlePayload { policies: None }
    }
}
