/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * The version of the OpenAPI document: v2
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CheckoutKeyInput {
    /// The type of checkout key to create. This may be either `deploy-key` or `user-key`.
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl CheckoutKeyInput {
    pub fn new(r#type: Type) -> CheckoutKeyInput {
        CheckoutKeyInput { r#type }
    }
}

/// The type of checkout key to create. This may be either `deploy-key` or `user-key`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "user-key")]
    UserKey,
    #[serde(rename = "deploy-key")]
    DeployKey,
}

impl Default for Type {
    fn default() -> Type {
        Self::UserKey
    }
}
