/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * The version of the OpenAPI document: v2
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Collaboration {
    /// The UUID of the organization
    #[serde(rename = "id", deserialize_with = "Option::deserialize")]
    pub id: Option<uuid::Uuid>,
    /// The VCS provider
    #[serde(rename = "vcs-type")]
    pub vcs_type: String,
    /// The name of the organization
    #[serde(rename = "name")]
    pub name: String,
    /// URL to the user's avatar on the VCS
    #[serde(rename = "avatar_url")]
    pub avatar_url: String,
    /// The slug of the organization
    #[serde(rename = "slug")]
    pub slug: String,
}

impl Collaboration {
    pub fn new(
        id: Option<uuid::Uuid>,
        vcs_type: String,
        name: String,
        avatar_url: String,
        slug: String,
    ) -> Collaboration {
        Collaboration {
            id,
            vcs_type,
            name,
            avatar_url,
            slug,
        }
    }
}
