/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * The version of the OpenAPI document: v2
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContinuePipelineRequest {
    /// A pipeline continuation key.
    #[serde(rename = "continuation-key")]
    pub continuation_key: String,
    /// A configuration string for the pipeline.
    #[serde(rename = "configuration")]
    pub configuration: String,
    /// An object containing pipeline parameters and their values.
    #[serde(rename = "parameters", skip_serializing_if = "Option::is_none")]
    pub parameters: Option<
        ::std::collections::HashMap<String, crate::models::ContinuePipelineRequestParametersValue>,
    >,
}

impl ContinuePipelineRequest {
    pub fn new(continuation_key: String, configuration: String) -> ContinuePipelineRequest {
        ContinuePipelineRequest {
            continuation_key,
            configuration,
            parameters: None,
        }
    }
}
