/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * The version of the OpenAPI document: v2
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContinuePipelineRequestParametersValue {}

impl ContinuePipelineRequestParametersValue {
    pub fn new() -> ContinuePipelineRequestParametersValue {
        ContinuePipelineRequestParametersValue {}
    }
}
