/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * The version of the OpenAPI document: v2
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Context {
    /// The unique ID of the context.
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    /// The user defined name of the context.
    #[serde(rename = "name")]
    pub name: String,
    /// The date and time the context was created.
    #[serde(rename = "created_at")]
    pub created_at: String,
}

impl Context {
    pub fn new(id: uuid::Uuid, name: String, created_at: String) -> Context {
        Context {
            id,
            name,
            created_at,
        }
    }
}
