/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * The version of the OpenAPI document: v2
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateContextRequest {
    /// The user defined name of the context.
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "owner")]
    pub owner: Box<crate::models::CreateContextRequestOwner>,
}

impl CreateContextRequest {
    pub fn new(
        name: String,
        owner: crate::models::CreateContextRequestOwner,
    ) -> CreateContextRequest {
        CreateContextRequest {
            name,
            owner: Box::new(owner),
        }
    }
}
