/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * The version of the OpenAPI document: v2
 *
 * Generated by: https://openapi-generator.tech
 */

/// CreateWebhookRequestScope : The scope in which the relevant events that will trigger webhooks

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateWebhookRequestScope {
    /// ID of the scope being used (at the moment, only project ID is supported)
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    /// Type of the scope being used
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl CreateWebhookRequestScope {
    /// The scope in which the relevant events that will trigger webhooks
    pub fn new(id: uuid::Uuid, r#type: Type) -> CreateWebhookRequestScope {
        CreateWebhookRequestScope { id, r#type }
    }
}

/// Type of the scope being used
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "project")]
    Project,
}

impl Default for Type {
    fn default() -> Type {
        Self::Project
    }
}
