/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * The version of the OpenAPI document: v2
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DecisionLogMetadataVcs {
    #[serde(rename = "branch", skip_serializing_if = "Option::is_none")]
    pub branch: Option<String>,
    #[serde(
        rename = "origin_repository_url",
        skip_serializing_if = "Option::is_none"
    )]
    pub origin_repository_url: Option<String>,
    #[serde(rename = "release_tag", skip_serializing_if = "Option::is_none")]
    pub release_tag: Option<String>,
    #[serde(
        rename = "target_repository_url",
        skip_serializing_if = "Option::is_none"
    )]
    pub target_repository_url: Option<String>,
}

impl DecisionLogMetadataVcs {
    pub fn new() -> DecisionLogMetadataVcs {
        DecisionLogMetadataVcs {
            branch: None,
            origin_repository_url: None,
            release_tag: None,
            target_repository_url: None,
        }
    }
}
