/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * The version of the OpenAPI document: v2
 *
 * Generated by: https://openapi-generator.tech
 */

/// EnvironmentVariable : An environment variable is a map containing a value and an optional timestamp.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct EnvironmentVariable {
    /// The name of the environment variable.
    #[serde(rename = "name")]
    pub name: String,
    /// The value of the environment variable.
    #[serde(rename = "value")]
    pub value: String,
    /// The creation timestamp of the environment variable.
    #[serde(
        rename = "created-at",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub created_at: Option<Option<serde_json::Value>>,
}

impl EnvironmentVariable {
    /// An environment variable is a map containing a value and an optional timestamp.
    pub fn new(name: String, value: String) -> EnvironmentVariable {
        EnvironmentVariable {
            name,
            value,
            created_at: None,
        }
    }
}
