/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * The version of the OpenAPI document: v2
 *
 * Generated by: https://openapi-generator.tech
 */

/// EnvironmentVariable1 : An environment variable request requires a name and a value

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct EnvironmentVariable1 {
    /// The name of the environment variable.
    #[serde(rename = "name")]
    pub name: String,
    /// The value of the environment variable.
    #[serde(rename = "value")]
    pub value: String,
}

impl EnvironmentVariable1 {
    /// An environment variable request requires a name and a value
    pub fn new(name: String, value: String) -> EnvironmentVariable1 {
        EnvironmentVariable1 { name, value }
    }
}
