/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * The version of the OpenAPI document: v2
 *
 * Generated by: https://openapi-generator.tech
 */

/// GetJobTimeseries200ResponseItemsInnerMetricsDurationMetrics : Metrics relating to the duration of runs for a workflow.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetJobTimeseries200ResponseItemsInnerMetricsDurationMetrics {
    /// The minimum duration, in seconds, among a group of runs.
    #[serde(rename = "min", deserialize_with = "Option::deserialize")]
    pub min: Option<i64>,
    /// The median duration, in seconds, among a group of runs.
    #[serde(rename = "median", deserialize_with = "Option::deserialize")]
    pub median: Option<i64>,
    /// The max duration, in seconds, among a group of runs.
    #[serde(rename = "max", deserialize_with = "Option::deserialize")]
    pub max: Option<i64>,
    /// The 95th percentile duration, in seconds, among a group of runs.
    #[serde(rename = "p95", deserialize_with = "Option::deserialize")]
    pub p95: Option<i64>,
    /// The total duration, in seconds, added across a group of runs.
    #[serde(rename = "total", deserialize_with = "Option::deserialize")]
    pub total: Option<i64>,
}

impl GetJobTimeseries200ResponseItemsInnerMetricsDurationMetrics {
    /// Metrics relating to the duration of runs for a workflow.
    pub fn new(
        min: Option<i64>,
        median: Option<i64>,
        max: Option<i64>,
        p95: Option<i64>,
        total: Option<i64>,
    ) -> GetJobTimeseries200ResponseItemsInnerMetricsDurationMetrics {
        GetJobTimeseries200ResponseItemsInnerMetricsDurationMetrics {
            min,
            median,
            max,
            p95,
            total,
        }
    }
}
