/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * The version of the OpenAPI document: v2
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetProjectWorkflowMetrics200ResponseItemsInner {
    /// The name of the workflow.
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "metrics")]
    pub metrics: Box<crate::models::GetProjectWorkflowMetrics200ResponseItemsInnerMetrics>,
    /// The timestamp of the first build within the requested reporting window.
    #[serde(rename = "window_start")]
    pub window_start: String,
    /// The timestamp of the last build within the requested reporting window.
    #[serde(rename = "window_end")]
    pub window_end: String,
    /// The unique ID of the project
    #[serde(rename = "project_id", deserialize_with = "Option::deserialize")]
    pub project_id: Option<serde_json::Value>,
}

impl GetProjectWorkflowMetrics200ResponseItemsInner {
    pub fn new(
        name: String,
        metrics: crate::models::GetProjectWorkflowMetrics200ResponseItemsInnerMetrics,
        window_start: String,
        window_end: String,
        project_id: Option<serde_json::Value>,
    ) -> GetProjectWorkflowMetrics200ResponseItemsInner {
        GetProjectWorkflowMetrics200ResponseItemsInner {
            name,
            metrics: Box::new(metrics),
            window_start,
            window_end,
            project_id,
        }
    }
}
