/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * The version of the OpenAPI document: v2
 *
 * Generated by: https://openapi-generator.tech
 */

/// GetProjectWorkflowTestMetrics200ResponseTestRunsInnerTestCounts : Test counts for a given pipeline number

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetProjectWorkflowTestMetrics200ResponseTestRunsInnerTestCounts {
    /// The number of tests with the error status
    #[serde(rename = "error")]
    pub error: i64,
    /// The number of tests with the failure status
    #[serde(rename = "failure")]
    pub failure: i64,
    /// The number of tests with the skipped status
    #[serde(rename = "skipped")]
    pub skipped: i64,
    /// The number of tests with the success status
    #[serde(rename = "success")]
    pub success: i64,
    /// The total number of tests
    #[serde(rename = "total")]
    pub total: i64,
}

impl GetProjectWorkflowTestMetrics200ResponseTestRunsInnerTestCounts {
    /// Test counts for a given pipeline number
    pub fn new(
        error: i64,
        failure: i64,
        skipped: i64,
        success: i64,
        total: i64,
    ) -> GetProjectWorkflowTestMetrics200ResponseTestRunsInnerTestCounts {
        GetProjectWorkflowTestMetrics200ResponseTestRunsInnerTestCounts {
            error,
            failure,
            skipped,
            success,
            total,
        }
    }
}
