/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * The version of the OpenAPI document: v2
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetProjectWorkflowJobMetrics200ResponseItemsInner {
    /// The name of the job.
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "metrics")]
    pub metrics: Box<crate::models::GetProjectWorkflowJobMetrics200ResponseItemsInnerMetrics>,
    /// The timestamp of the first build within the requested reporting window.
    #[serde(rename = "window_start")]
    pub window_start: String,
    /// The timestamp of the last build within the requested reporting window.
    #[serde(rename = "window_end")]
    pub window_end: String,
}

impl GetProjectWorkflowJobMetrics200ResponseItemsInner {
    pub fn new(
        name: String,
        metrics: crate::models::GetProjectWorkflowJobMetrics200ResponseItemsInnerMetrics,
        window_start: String,
        window_end: String,
    ) -> GetProjectWorkflowJobMetrics200ResponseItemsInner {
        GetProjectWorkflowJobMetrics200ResponseItemsInner {
            name,
            metrics: Box::new(metrics),
            window_start,
            window_end,
        }
    }
}
