/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * The version of the OpenAPI document: v2
 *
 * Generated by: https://openapi-generator.tech
 */

/// GetJobTimeseries200Response : Project level timeseries metrics response

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetJobTimeseries200Response {
    /// A token to pass as a `page-token` query parameter to return the next page of results.
    #[serde(rename = "next_page_token", deserialize_with = "Option::deserialize")]
    pub next_page_token: Option<String>,
    /// Aggregate metrics for a workflow at a time granularity
    #[serde(rename = "items")]
    pub items: Vec<crate::models::GetJobTimeseries200ResponseItemsInner>,
}

impl GetJobTimeseries200Response {
    /// Project level timeseries metrics response
    pub fn new(
        next_page_token: Option<String>,
        items: Vec<crate::models::GetJobTimeseries200ResponseItemsInner>,
    ) -> GetJobTimeseries200Response {
        GetJobTimeseries200Response {
            next_page_token,
            items,
        }
    }
}
