/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * The version of the OpenAPI document: v2
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetOrgSummaryData200ResponseOrgProjectDataInner {
    /// The name of the project.
    #[serde(rename = "project_name")]
    pub project_name: String,
    #[serde(rename = "metrics")]
    pub metrics: Box<crate::models::GetOrgSummaryData200ResponseOrgProjectDataInnerMetrics>,
    #[serde(rename = "trends")]
    pub trends: Box<crate::models::GetOrgSummaryData200ResponseOrgProjectDataInnerTrends>,
}

impl GetOrgSummaryData200ResponseOrgProjectDataInner {
    pub fn new(
        project_name: String,
        metrics: crate::models::GetOrgSummaryData200ResponseOrgProjectDataInnerMetrics,
        trends: crate::models::GetOrgSummaryData200ResponseOrgProjectDataInnerTrends,
    ) -> GetOrgSummaryData200ResponseOrgProjectDataInner {
        GetOrgSummaryData200ResponseOrgProjectDataInner {
            project_name,
            metrics: Box::new(metrics),
            trends: Box::new(trends),
        }
    }
}
