/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * The version of the OpenAPI document: v2
 *
 * Generated by: https://openapi-generator.tech
 */

/// GetOrgSummaryData200ResponseOrgData : Aggregated metrics for an org, with trends.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetOrgSummaryData200ResponseOrgData {
    #[serde(rename = "metrics")]
    pub metrics: Box<crate::models::GetOrgSummaryData200ResponseOrgDataMetrics>,
    #[serde(rename = "trends")]
    pub trends: Box<crate::models::GetOrgSummaryData200ResponseOrgDataTrends>,
}

impl GetOrgSummaryData200ResponseOrgData {
    /// Aggregated metrics for an org, with trends.
    pub fn new(
        metrics: crate::models::GetOrgSummaryData200ResponseOrgDataMetrics,
        trends: crate::models::GetOrgSummaryData200ResponseOrgDataTrends,
    ) -> GetOrgSummaryData200ResponseOrgData {
        GetOrgSummaryData200ResponseOrgData {
            metrics: Box::new(metrics),
            trends: Box::new(trends),
        }
    }
}
