/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * The version of the OpenAPI document: v2
 *
 * Generated by: https://openapi-generator.tech
 */

/// GetProjectWorkflowsPageData200ResponseProjectWorkflowDataInnerTrends : Trends aggregated across a workflow or branch for a project.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetProjectWorkflowsPageData200ResponseProjectWorkflowDataInnerTrends {
    /// The trend value for total credits consumed.
    #[serde(rename = "total_credits_used")]
    pub total_credits_used: f32,
    /// The 95th percentile duration among a group of workflow runs.
    #[serde(rename = "p95_duration_secs")]
    pub p95_duration_secs: f32,
    /// The trend value for total number of runs.
    #[serde(rename = "total_runs")]
    pub total_runs: f32,
    /// The trend value for the success rate.
    #[serde(rename = "success_rate")]
    pub success_rate: f32,
}

impl GetProjectWorkflowsPageData200ResponseProjectWorkflowDataInnerTrends {
    /// Trends aggregated across a workflow or branch for a project.
    pub fn new(
        total_credits_used: f32,
        p95_duration_secs: f32,
        total_runs: f32,
        success_rate: f32,
    ) -> GetProjectWorkflowsPageData200ResponseProjectWorkflowDataInnerTrends {
        GetProjectWorkflowsPageData200ResponseProjectWorkflowDataInnerTrends {
            total_credits_used,
            p95_duration_secs,
            total_runs,
            success_rate,
        }
    }
}
