/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * The version of the OpenAPI document: v2
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetOrgClaims400Response {
    #[serde(rename = "error")]
    pub error: String,
}

impl GetOrgClaims400Response {
    pub fn new(error: String) -> GetOrgClaims400Response {
        GetOrgClaims400Response { error }
    }
}
