/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * The version of the OpenAPI document: v2
 *
 * Generated by: https://openapi-generator.tech
 */

/// GetProjectWorkflowJobMetrics200ResponseItemsInnerMetrics : Metrics relating to a workflow job's runs.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetProjectWorkflowJobMetrics200ResponseItemsInnerMetrics {
    /// The total number of runs, including runs that are still on-hold or running.
    #[serde(rename = "total_runs")]
    pub total_runs: i64,
    /// The number of failed runs.
    #[serde(rename = "failed_runs")]
    pub failed_runs: i64,
    /// The number of successful runs.
    #[serde(rename = "successful_runs")]
    pub successful_runs: i64,
    #[serde(rename = "duration_metrics")]
    pub duration_metrics:
        Box<crate::models::GetProjectWorkflowJobMetrics200ResponseItemsInnerMetricsDurationMetrics>,
    #[serde(rename = "success_rate")]
    pub success_rate: f32,
    /// The total credits consumed by the job in the aggregation window. Note that Insights is not a real time financial reporting tool and should not be used for credit reporting.
    #[serde(rename = "total_credits_used")]
    pub total_credits_used: i64,
    /// The average number of runs per day.
    #[serde(rename = "throughput")]
    pub throughput: f32,
}

impl GetProjectWorkflowJobMetrics200ResponseItemsInnerMetrics {
    /// Metrics relating to a workflow job's runs.
    pub fn new(
        total_runs: i64,
        failed_runs: i64,
        successful_runs: i64,
        duration_metrics: crate::models::GetProjectWorkflowJobMetrics200ResponseItemsInnerMetricsDurationMetrics,
        success_rate: f32,
        total_credits_used: i64,
        throughput: f32,
    ) -> GetProjectWorkflowJobMetrics200ResponseItemsInnerMetrics {
        GetProjectWorkflowJobMetrics200ResponseItemsInnerMetrics {
            total_runs,
            failed_runs,
            successful_runs,
            duration_metrics: Box::new(duration_metrics),
            success_rate,
            total_credits_used,
            throughput,
        }
    }
}
