/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * The version of the OpenAPI document: v2
 *
 * Generated by: https://openapi-generator.tech
 */

/// GetProjectWorkflowMetrics200Response : Paginated workflow summary metrics.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetProjectWorkflowMetrics200Response {
    /// Workflow summary metrics.
    #[serde(rename = "items")]
    pub items: Vec<crate::models::GetProjectWorkflowMetrics200ResponseItemsInner>,
    /// A token to pass as a `page-token` query parameter to return the next page of results.
    #[serde(rename = "next_page_token", deserialize_with = "Option::deserialize")]
    pub next_page_token: Option<String>,
}

impl GetProjectWorkflowMetrics200Response {
    /// Paginated workflow summary metrics.
    pub fn new(
        items: Vec<crate::models::GetProjectWorkflowMetrics200ResponseItemsInner>,
        next_page_token: Option<String>,
    ) -> GetProjectWorkflowMetrics200Response {
        GetProjectWorkflowMetrics200Response {
            items,
            next_page_token,
        }
    }
}
