/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * The version of the OpenAPI document: v2
 *
 * Generated by: https://openapi-generator.tech
 */

/// GetWorkflowSummary200Response : Workflow level aggregated metrics and trends response

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetWorkflowSummary200Response {
    #[serde(rename = "metrics")]
    pub metrics: Box<crate::models::GetWorkflowSummary200ResponseMetrics>,
    #[serde(rename = "trends")]
    pub trends: Box<crate::models::GetWorkflowSummary200ResponseTrends>,
    /// A list of all the workflow names for a given project.
    #[serde(rename = "workflow_names")]
    pub workflow_names: Vec<String>,
}

impl GetWorkflowSummary200Response {
    /// Workflow level aggregated metrics and trends response
    pub fn new(
        metrics: crate::models::GetWorkflowSummary200ResponseMetrics,
        trends: crate::models::GetWorkflowSummary200ResponseTrends,
        workflow_names: Vec<String>,
    ) -> GetWorkflowSummary200Response {
        GetWorkflowSummary200Response {
            metrics: Box::new(metrics),
            trends: Box::new(trends),
            workflow_names,
        }
    }
}
