/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * The version of the OpenAPI document: v2
 *
 * Generated by: https://openapi-generator.tech
 */

/// GetProjectWorkflowsPageData200ResponseProjectData : Metrics and trends data aggregated for a given project.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetProjectWorkflowsPageData200ResponseProjectData {
    #[serde(rename = "metrics")]
    pub metrics: Box<crate::models::GetProjectWorkflowsPageData200ResponseProjectDataMetrics>,
    #[serde(rename = "trends")]
    pub trends: Box<crate::models::GetProjectWorkflowsPageData200ResponseProjectDataTrends>,
}

impl GetProjectWorkflowsPageData200ResponseProjectData {
    /// Metrics and trends data aggregated for a given project.
    pub fn new(
        metrics: crate::models::GetProjectWorkflowsPageData200ResponseProjectDataMetrics,
        trends: crate::models::GetProjectWorkflowsPageData200ResponseProjectDataTrends,
    ) -> GetProjectWorkflowsPageData200ResponseProjectData {
        GetProjectWorkflowsPageData200ResponseProjectData {
            metrics: Box::new(metrics),
            trends: Box::new(trends),
        }
    }
}
