/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * The version of the OpenAPI document: v2
 *
 * Generated by: https://openapi-generator.tech
 */

/// GetOrgSummaryData200ResponseOrgProjectDataInnerMetrics : Metrics for a single project, across all branches.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetOrgSummaryData200ResponseOrgProjectDataInnerMetrics {
    /// The total credits consumed over the current timeseries interval.
    #[serde(rename = "total_credits_used")]
    pub total_credits_used: i64,
    /// Total duration, in seconds.
    #[serde(rename = "total_duration_secs")]
    pub total_duration_secs: i64,
    /// The total number of runs, including runs that are still on-hold or running.
    #[serde(rename = "total_runs")]
    pub total_runs: i64,
    #[serde(rename = "success_rate")]
    pub success_rate: f32,
}

impl GetOrgSummaryData200ResponseOrgProjectDataInnerMetrics {
    /// Metrics for a single project, across all branches.
    pub fn new(
        total_credits_used: i64,
        total_duration_secs: i64,
        total_runs: i64,
        success_rate: f32,
    ) -> GetOrgSummaryData200ResponseOrgProjectDataInnerMetrics {
        GetOrgSummaryData200ResponseOrgProjectDataInnerMetrics {
            total_credits_used,
            total_duration_secs,
            total_runs,
            success_rate,
        }
    }
}
