/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * The version of the OpenAPI document: v2
 *
 * Generated by: https://openapi-generator.tech
 */

/// GetWebhooks200Response : A list of webhooks

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetWebhooks200Response {
    #[serde(rename = "items")]
    pub items: Vec<crate::models::Webhook>,
    /// A token to pass as a `page-token` query parameter to return the next page of results.
    #[serde(rename = "next_page_token", deserialize_with = "Option::deserialize")]
    pub next_page_token: Option<String>,
}

impl GetWebhooks200Response {
    /// A list of webhooks
    pub fn new(
        items: Vec<crate::models::Webhook>,
        next_page_token: Option<String>,
    ) -> GetWebhooks200Response {
        GetWebhooks200Response {
            items,
            next_page_token,
        }
    }
}
