/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * The version of the OpenAPI document: v2
 *
 * Generated by: https://openapi-generator.tech
 */

/// GetProjectWorkflowJobMetrics200Response : Paginated workflow job summary metrics.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetProjectWorkflowJobMetrics200Response {
    /// Job summary metrics.
    #[serde(rename = "items")]
    pub items: Vec<crate::models::GetProjectWorkflowJobMetrics200ResponseItemsInner>,
    /// A token to pass as a `page-token` query parameter to return the next page of results.
    #[serde(rename = "next_page_token", deserialize_with = "Option::deserialize")]
    pub next_page_token: Option<String>,
}

impl GetProjectWorkflowJobMetrics200Response {
    /// Paginated workflow job summary metrics.
    pub fn new(
        items: Vec<crate::models::GetProjectWorkflowJobMetrics200ResponseItemsInner>,
        next_page_token: Option<String>,
    ) -> GetProjectWorkflowJobMetrics200Response {
        GetProjectWorkflowJobMetrics200Response {
            items,
            next_page_token,
        }
    }
}
