/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * The version of the OpenAPI document: v2
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetProjectWorkflowTestMetrics200ResponseTestRunsInner {
    /// The number of the pipeline associated with the provided test counts
    #[serde(rename = "pipeline_number")]
    pub pipeline_number: i64,
    /// The ID of the workflow associated with the provided test counts
    #[serde(rename = "workflow_id", deserialize_with = "Option::deserialize")]
    pub workflow_id: Option<serde_json::Value>,
    /// The success rate calculated from test counts
    #[serde(rename = "success_rate")]
    pub success_rate: f32,
    #[serde(rename = "test_counts")]
    pub test_counts:
        Box<crate::models::GetProjectWorkflowTestMetrics200ResponseTestRunsInnerTestCounts>,
}

impl GetProjectWorkflowTestMetrics200ResponseTestRunsInner {
    pub fn new(
        pipeline_number: i64,
        workflow_id: Option<serde_json::Value>,
        success_rate: f32,
        test_counts: crate::models::GetProjectWorkflowTestMetrics200ResponseTestRunsInnerTestCounts,
    ) -> GetProjectWorkflowTestMetrics200ResponseTestRunsInner {
        GetProjectWorkflowTestMetrics200ResponseTestRunsInner {
            pipeline_number,
            workflow_id,
            success_rate,
            test_counts: Box::new(test_counts),
        }
    }
}
