/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * The version of the OpenAPI document: v2
 *
 * Generated by: https://openapi-generator.tech
 */

/// GetProjectWorkflowsPageData200ResponseProjectWorkflowDataInnerMetrics : Metrics aggregated across a workflow or branchfor a project.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetProjectWorkflowsPageData200ResponseProjectWorkflowDataInnerMetrics {
    /// The total credits consumed over the current timeseries interval.
    #[serde(rename = "total_credits_used")]
    pub total_credits_used: i64,
    /// The 95th percentile duration among a group of workflow runs.
    #[serde(rename = "p95_duration_secs")]
    pub p95_duration_secs: f32,
    /// The total number of runs, including runs that are still on-hold or running.
    #[serde(rename = "total_runs")]
    pub total_runs: i64,
    #[serde(rename = "success_rate")]
    pub success_rate: f32,
}

impl GetProjectWorkflowsPageData200ResponseProjectWorkflowDataInnerMetrics {
    /// Metrics aggregated across a workflow or branchfor a project.
    pub fn new(
        total_credits_used: i64,
        p95_duration_secs: f32,
        total_runs: i64,
        success_rate: f32,
    ) -> GetProjectWorkflowsPageData200ResponseProjectWorkflowDataInnerMetrics {
        GetProjectWorkflowsPageData200ResponseProjectWorkflowDataInnerMetrics {
            total_credits_used,
            p95_duration_secs,
            total_runs,
            success_rate,
        }
    }
}
