/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * The version of the OpenAPI document: v2
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetJobTimeseries200ResponseItemsInner {
    /// The name of the workflow.
    #[serde(rename = "name")]
    pub name: String,
    /// The start time for the earliest execution included in the metrics.
    #[serde(rename = "min_started_at")]
    pub min_started_at: String,
    /// The end time of the last execution included in the metrics.
    #[serde(rename = "max_ended_at")]
    pub max_ended_at: String,
    /// The start of the interval for timeseries metrics.
    #[serde(rename = "timestamp")]
    pub timestamp: String,
    #[serde(rename = "metrics")]
    pub metrics: Box<crate::models::GetJobTimeseries200ResponseItemsInnerMetrics>,
}

impl GetJobTimeseries200ResponseItemsInner {
    pub fn new(
        name: String,
        min_started_at: String,
        max_ended_at: String,
        timestamp: String,
        metrics: crate::models::GetJobTimeseries200ResponseItemsInnerMetrics,
    ) -> GetJobTimeseries200ResponseItemsInner {
        GetJobTimeseries200ResponseItemsInner {
            name,
            min_started_at,
            max_ended_at,
            timestamp,
            metrics: Box::new(metrics),
        }
    }
}
