/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * The version of the OpenAPI document: v2
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetProjectWorkflowTestMetrics200ResponseMostFailedTestsInner {
    /// The 95th percentile duration, in seconds, among a group of test runs.
    #[serde(rename = "p95_duration", deserialize_with = "Option::deserialize")]
    pub p95_duration: Option<f64>,
    /// The total number of times the test was run.
    #[serde(rename = "total_runs")]
    pub total_runs: i64,
    /// The class the test belongs to.
    #[serde(rename = "classname", deserialize_with = "Option::deserialize")]
    pub classname: Option<String>,
    /// The number of times the test failed
    #[serde(rename = "failed_runs")]
    pub failed_runs: i64,
    /// Whether the test is flaky.
    #[serde(rename = "flaky")]
    pub flaky: bool,
    /// The source of the test.
    #[serde(rename = "source", deserialize_with = "Option::deserialize")]
    pub source: Option<String>,
    /// The file the test belongs to.
    #[serde(rename = "file", deserialize_with = "Option::deserialize")]
    pub file: Option<String>,
    /// The name of the job.
    #[serde(rename = "job_name")]
    pub job_name: String,
    /// The name of the test.
    #[serde(rename = "test_name")]
    pub test_name: String,
}

impl GetProjectWorkflowTestMetrics200ResponseMostFailedTestsInner {
    pub fn new(
        p95_duration: Option<f64>,
        total_runs: i64,
        classname: Option<String>,
        failed_runs: i64,
        flaky: bool,
        source: Option<String>,
        file: Option<String>,
        job_name: String,
        test_name: String,
    ) -> GetProjectWorkflowTestMetrics200ResponseMostFailedTestsInner {
        GetProjectWorkflowTestMetrics200ResponseMostFailedTestsInner {
            p95_duration,
            total_runs,
            classname,
            failed_runs,
            flaky,
            source,
            file,
            job_name,
            test_name,
        }
    }
}
