/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * The version of the OpenAPI document: v2
 *
 * Generated by: https://openapi-generator.tech
 */

/// GetProjectWorkflowMetrics200ResponseItemsInnerMetricsDurationMetrics : Metrics relating to the duration of runs for a workflow.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetProjectWorkflowMetrics200ResponseItemsInnerMetricsDurationMetrics {
    /// The minimum duration, in seconds, among a group of runs.
    #[serde(rename = "min", deserialize_with = "Option::deserialize")]
    pub min: Option<i64>,
    /// The mean duration, in seconds, among a group of runs.
    #[serde(rename = "mean", deserialize_with = "Option::deserialize")]
    pub mean: Option<i64>,
    /// The median duration, in seconds, among a group of runs.
    #[serde(rename = "median", deserialize_with = "Option::deserialize")]
    pub median: Option<i64>,
    /// The 95th percentile duration, in seconds, among a group of runs.
    #[serde(rename = "p95", deserialize_with = "Option::deserialize")]
    pub p95: Option<i64>,
    /// The max duration, in seconds, among a group of runs.
    #[serde(rename = "max", deserialize_with = "Option::deserialize")]
    pub max: Option<i64>,
    /// The standard deviation, in seconds, among a group of runs.
    #[serde(
        rename = "standard_deviation",
        deserialize_with = "Option::deserialize"
    )]
    pub standard_deviation: Option<f32>,
}

impl GetProjectWorkflowMetrics200ResponseItemsInnerMetricsDurationMetrics {
    /// Metrics relating to the duration of runs for a workflow.
    pub fn new(
        min: Option<i64>,
        mean: Option<i64>,
        median: Option<i64>,
        p95: Option<i64>,
        max: Option<i64>,
        standard_deviation: Option<f32>,
    ) -> GetProjectWorkflowMetrics200ResponseItemsInnerMetricsDurationMetrics {
        GetProjectWorkflowMetrics200ResponseItemsInnerMetricsDurationMetrics {
            min,
            mean,
            median,
            p95,
            max,
            standard_deviation,
        }
    }
}
