/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * The version of the OpenAPI document: v2
 *
 * Generated by: https://openapi-generator.tech
 */

/// GetProjectWorkflowsPageData200ResponseProjectDataMetrics : Metrics aggregated across all workflows and branches for a project.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetProjectWorkflowsPageData200ResponseProjectDataMetrics {
    /// The total number of runs, including runs that are still on-hold or running.
    #[serde(rename = "total_runs")]
    pub total_runs: i64,
    /// Total duration, in seconds.
    #[serde(rename = "total_duration_secs")]
    pub total_duration_secs: i64,
    /// The total credits consumed over the current timeseries interval.
    #[serde(rename = "total_credits_used")]
    pub total_credits_used: i64,
    #[serde(rename = "success_rate")]
    pub success_rate: f32,
    /// The average number of runs per day.
    #[serde(rename = "throughput")]
    pub throughput: f32,
}

impl GetProjectWorkflowsPageData200ResponseProjectDataMetrics {
    /// Metrics aggregated across all workflows and branches for a project.
    pub fn new(
        total_runs: i64,
        total_duration_secs: i64,
        total_credits_used: i64,
        success_rate: f32,
        throughput: f32,
    ) -> GetProjectWorkflowsPageData200ResponseProjectDataMetrics {
        GetProjectWorkflowsPageData200ResponseProjectDataMetrics {
            total_runs,
            total_duration_secs,
            total_credits_used,
            success_rate,
            throughput,
        }
    }
}
