/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * The version of the OpenAPI document: v2
 *
 * Generated by: https://openapi-generator.tech
 */

/// GetProjectWorkflowTestMetrics200Response : Project level test metrics response

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetProjectWorkflowTestMetrics200Response {
    /// The average number of tests executed per run
    #[serde(rename = "average_test_count")]
    pub average_test_count: i64,
    /// Metrics for the most frequently failing tests
    #[serde(rename = "most_failed_tests")]
    pub most_failed_tests:
        Vec<crate::models::GetProjectWorkflowTestMetrics200ResponseMostFailedTestsInner>,
    /// The number of tests with the same success rate being omitted from most_failed_tests
    #[serde(rename = "most_failed_tests_extra")]
    pub most_failed_tests_extra: i64,
    /// Metrics for the slowest running tests
    #[serde(rename = "slowest_tests")]
    pub slowest_tests:
        Vec<crate::models::GetProjectWorkflowTestMetrics200ResponseMostFailedTestsInner>,
    /// The number of tests with the same duration rate being omitted from slowest_tests
    #[serde(rename = "slowest_tests_extra")]
    pub slowest_tests_extra: i64,
    /// The total number of test runs
    #[serde(rename = "total_test_runs")]
    pub total_test_runs: i64,
    /// Test counts grouped by pipeline number and workflow id
    #[serde(rename = "test_runs")]
    pub test_runs: Vec<crate::models::GetProjectWorkflowTestMetrics200ResponseTestRunsInner>,
}

impl GetProjectWorkflowTestMetrics200Response {
    /// Project level test metrics response
    pub fn new(
        average_test_count: i64,
        most_failed_tests: Vec<
            crate::models::GetProjectWorkflowTestMetrics200ResponseMostFailedTestsInner,
        >,
        most_failed_tests_extra: i64,
        slowest_tests: Vec<
            crate::models::GetProjectWorkflowTestMetrics200ResponseMostFailedTestsInner,
        >,
        slowest_tests_extra: i64,
        total_test_runs: i64,
        test_runs: Vec<crate::models::GetProjectWorkflowTestMetrics200ResponseTestRunsInner>,
    ) -> GetProjectWorkflowTestMetrics200Response {
        GetProjectWorkflowTestMetrics200Response {
            average_test_count,
            most_failed_tests,
            most_failed_tests_extra,
            slowest_tests,
            slowest_tests_extra,
            total_test_runs,
            test_runs,
        }
    }
}
