/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * The version of the OpenAPI document: v2
 *
 * Generated by: https://openapi-generator.tech
 */

/// GetProjectWorkflowMetrics200ResponseItemsInnerMetrics : Metrics relating to a workflow's runs.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetProjectWorkflowMetrics200ResponseItemsInnerMetrics {
    /// The total number of runs, including runs that are still on-hold or running.
    #[serde(rename = "total_runs")]
    pub total_runs: i64,
    /// The number of successful runs.
    #[serde(rename = "successful_runs")]
    pub successful_runs: i64,
    /// The mean time to recovery (mean time between failures and their next success) in seconds.
    #[serde(rename = "mttr", deserialize_with = "Option::deserialize")]
    pub mttr: Option<i64>,
    /// The total credits consumed by the workflow in the aggregation window. Note that Insights is not a real time financial reporting tool and should not be used for credit reporting.
    #[serde(
        rename = "total_credits_used",
        deserialize_with = "Option::deserialize"
    )]
    pub total_credits_used: Option<i64>,
    /// The number of failed runs.
    #[serde(rename = "failed_runs")]
    pub failed_runs: i64,
    #[serde(rename = "success_rate")]
    pub success_rate: f32,
    #[serde(rename = "duration_metrics")]
    pub duration_metrics:
        Box<crate::models::GetProjectWorkflowMetrics200ResponseItemsInnerMetricsDurationMetrics>,
    /// The number of recovered workflow executions per day.
    #[serde(rename = "total_recoveries", deserialize_with = "Option::deserialize")]
    pub total_recoveries: Option<i64>,
    /// The average number of runs per day.
    #[serde(rename = "throughput")]
    pub throughput: f32,
}

impl GetProjectWorkflowMetrics200ResponseItemsInnerMetrics {
    /// Metrics relating to a workflow's runs.
    pub fn new(
        total_runs: i64,
        successful_runs: i64,
        mttr: Option<i64>,
        total_credits_used: Option<i64>,
        failed_runs: i64,
        success_rate: f32,
        duration_metrics: crate::models::GetProjectWorkflowMetrics200ResponseItemsInnerMetricsDurationMetrics,
        total_recoveries: Option<i64>,
        throughput: f32,
    ) -> GetProjectWorkflowMetrics200ResponseItemsInnerMetrics {
        GetProjectWorkflowMetrics200ResponseItemsInnerMetrics {
            total_runs,
            successful_runs,
            mttr,
            total_credits_used,
            failed_runs,
            success_rate,
            duration_metrics: Box::new(duration_metrics),
            total_recoveries,
            throughput,
        }
    }
}
