/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * The version of the OpenAPI document: v2
 *
 * Generated by: https://openapi-generator.tech
 */

/// JobDetailsLatestWorkflow : Info about the latest workflow the job was a part of.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct JobDetailsLatestWorkflow {
    /// The unique ID of the workflow.
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    /// The name of the workflow.
    #[serde(rename = "name")]
    pub name: String,
}

impl JobDetailsLatestWorkflow {
    /// Info about the latest workflow the job was a part of.
    pub fn new(id: uuid::Uuid, name: String) -> JobDetailsLatestWorkflow {
        JobDetailsLatestWorkflow { id, name }
    }
}
