/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * The version of the OpenAPI document: v2
 *
 * Generated by: https://openapi-generator.tech
 */

/// JobDetailsPipeline : Info about a pipeline the job is a part of.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct JobDetailsPipeline {
    /// The unique ID of the pipeline.
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
}

impl JobDetailsPipeline {
    /// Info about a pipeline the job is a part of.
    pub fn new(id: uuid::Uuid) -> JobDetailsPipeline {
        JobDetailsPipeline { id }
    }
}
