/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * The version of the OpenAPI document: v2
 *
 * Generated by: https://openapi-generator.tech
 */

/// JobDetailsContextsInner : Information about the context.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct JobDetailsContextsInner {
    /// The name of the context.
    #[serde(rename = "name")]
    pub name: String,
}

impl JobDetailsContextsInner {
    /// Information about the context.
    pub fn new(name: String) -> JobDetailsContextsInner {
        JobDetailsContextsInner { name }
    }
}
