/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * The version of the OpenAPI document: v2
 *
 * Generated by: https://openapi-generator.tech
 */

/// JobDetailsMessagesInner : Message from CircleCI execution platform.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct JobDetailsMessagesInner {
    /// Message type.
    #[serde(rename = "type")]
    pub r#type: String,
    /// Information describing message.
    #[serde(rename = "message")]
    pub message: String,
    /// Value describing the reason for message to be added to the job.
    #[serde(rename = "reason", skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
}

impl JobDetailsMessagesInner {
    /// Message from CircleCI execution platform.
    pub fn new(r#type: String, message: String) -> JobDetailsMessagesInner {
        JobDetailsMessagesInner {
            r#type,
            message,
            reason: None,
        }
    }
}
