/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * The version of the OpenAPI document: v2
 *
 * Generated by: https://openapi-generator.tech
 */

/// ListSchedulesForProject200Response : A sequence of schedules

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListSchedulesForProject200Response {
    #[serde(rename = "items")]
    pub items: Vec<crate::models::Schedule>,
    /// A token to pass as a `page-token` query parameter to return the next page of results.
    #[serde(rename = "next_page_token", deserialize_with = "Option::deserialize")]
    pub next_page_token: Option<String>,
}

impl ListSchedulesForProject200Response {
    /// A sequence of schedules
    pub fn new(
        items: Vec<crate::models::Schedule>,
        next_page_token: Option<String>,
    ) -> ListSchedulesForProject200Response {
        ListSchedulesForProject200Response {
            items,
            next_page_token,
        }
    }
}
