/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * The version of the OpenAPI document: v2
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct MakeDecisionRequest {
    #[serde(rename = "input")]
    pub input: String,
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<serde_json::Value>,
}

impl MakeDecisionRequest {
    pub fn new(input: String) -> MakeDecisionRequest {
        MakeDecisionRequest {
            input,
            metadata: None,
        }
    }
}
