/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * The version of the OpenAPI document: v2
 *
 * Generated by: https://openapi-generator.tech
 */

/// MessageResponse : message response

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct MessageResponse {
    /// A human-readable message
    #[serde(rename = "message")]
    pub message: String,
}

impl MessageResponse {
    /// message response
    pub fn new(message: String) -> MessageResponse {
        MessageResponse { message }
    }
}
