/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * The version of the OpenAPI document: v2
 *
 * Generated by: https://openapi-generator.tech
 */

/// PipelineTrigger : A summary of the trigger.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PipelineTrigger {
    /// The type of trigger.
    #[serde(rename = "type")]
    pub r#type: Type,
    /// The date and time the trigger was received.
    #[serde(rename = "received_at")]
    pub received_at: String,
    #[serde(rename = "actor")]
    pub actor: Box<crate::models::PipelineTriggerActor>,
}

impl PipelineTrigger {
    /// A summary of the trigger.
    pub fn new(
        r#type: Type,
        received_at: String,
        actor: crate::models::PipelineTriggerActor,
    ) -> PipelineTrigger {
        PipelineTrigger {
            r#type,
            received_at,
            actor: Box::new(actor),
        }
    }
}

/// The type of trigger.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "scheduled_pipeline")]
    ScheduledPipeline,
    #[serde(rename = "explicit")]
    Explicit,
    #[serde(rename = "api")]
    Api,
    #[serde(rename = "webhook")]
    Webhook,
}

impl Default for Type {
    fn default() -> Type {
        Self::ScheduledPipeline
    }
}
