/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * The version of the OpenAPI document: v2
 *
 * Generated by: https://openapi-generator.tech
 */

/// PipelineVcsCommit : The latest commit in the pipeline.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PipelineVcsCommit {
    /// The subject of the commit message.
    #[serde(rename = "subject", deserialize_with = "Option::deserialize")]
    pub subject: Option<String>,
    /// The body of the commit message.
    #[serde(rename = "body", deserialize_with = "Option::deserialize")]
    pub body: Option<String>,
}

impl PipelineVcsCommit {
    /// The latest commit in the pipeline.
    pub fn new(subject: Option<String>, body: Option<String>) -> PipelineVcsCommit {
        PipelineVcsCommit { subject, body }
    }
}
