/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * The version of the OpenAPI document: v2
 *
 * Generated by: https://openapi-generator.tech
 */

/// PipelineCreation : A pipeline creation response.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PipelineCreation {
    /// The unique ID of the pipeline.
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    /// The current state of the pipeline.
    #[serde(rename = "state")]
    pub state: State,
    /// The number of the pipeline.
    #[serde(rename = "number")]
    pub number: i64,
    /// The date and time the pipeline was created.
    #[serde(rename = "created_at")]
    pub created_at: String,
}

impl PipelineCreation {
    /// A pipeline creation response.
    pub fn new(id: uuid::Uuid, state: State, number: i64, created_at: String) -> PipelineCreation {
        PipelineCreation {
            id,
            state,
            number,
            created_at,
        }
    }
}

/// The current state of the pipeline.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum State {
    #[serde(rename = "created")]
    Created,
    #[serde(rename = "errored")]
    Errored,
    #[serde(rename = "setup-pending")]
    SetupPending,
    #[serde(rename = "setup")]
    Setup,
    #[serde(rename = "pending")]
    Pending,
}

impl Default for State {
    fn default() -> State {
        Self::Created
    }
}
