/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * The version of the OpenAPI document: v2
 *
 * Generated by: https://openapi-generator.tech
 */

/// PipelineConfig : The configuration strings for the pipeline.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PipelineConfig {
    /// The source configuration for the pipeline, before any config compilation has been performed. If there is no config, then this field will be empty.
    #[serde(rename = "source")]
    pub source: String,
    /// The compiled configuration for the pipeline, after all orb expansion has been performed. If there were errors processing the pipeline's configuration, then this field may be empty.
    #[serde(rename = "compiled")]
    pub compiled: String,
    /// The setup configuration for the pipeline used for Setup Workflows. If there were errors processing the pipeline's configuration or if setup workflows are not enabled, then this field should not exist
    #[serde(rename = "setup-config", skip_serializing_if = "Option::is_none")]
    pub setup_config: Option<String>,
    /// The compiled setup configuration for the pipeline, after all orb expansion has been performed. If there were errors processing the pipeline's setup workflows, then this field may be empty.
    #[serde(
        rename = "compiled-setup-config",
        skip_serializing_if = "Option::is_none"
    )]
    pub compiled_setup_config: Option<String>,
}

impl PipelineConfig {
    /// The configuration strings for the pipeline.
    pub fn new(source: String, compiled: String) -> PipelineConfig {
        PipelineConfig {
            source,
            compiled,
            setup_config: None,
            compiled_setup_config: None,
        }
    }
}
