/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * The version of the OpenAPI document: v2
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TestsResponseInner {
    /// The failure message associated with the test.
    #[serde(rename = "message", deserialize_with = "Option::deserialize")]
    pub message: Option<String>,
    /// The program that generated the test results
    #[serde(rename = "source")]
    pub source: String,
    /// The time it took to run the test in seconds
    #[serde(rename = "run_time")]
    pub run_time: f64,
    /// The file in which the test is defined.
    #[serde(rename = "file")]
    pub file: String,
    /// Indication of whether the test succeeded.
    #[serde(rename = "result")]
    pub result: String,
    /// The name of the test.
    #[serde(rename = "name")]
    pub name: String,
    /// The programmatic location of the test.
    #[serde(rename = "classname")]
    pub classname: String,
}

impl TestsResponseInner {
    pub fn new(
        message: Option<String>,
        source: String,
        run_time: f64,
        file: String,
        result: String,
        name: String,
        classname: String,
    ) -> TestsResponseInner {
        TestsResponseInner {
            message,
            source,
            run_time,
            file,
            result,
            name,
            classname,
        }
    }
}
