/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * The version of the OpenAPI document: v2
 *
 * Generated by: https://openapi-generator.tech
 */

/// User1 : The attribution actor who will run the scheduled pipeline.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct User1 {
    /// The unique ID of the user.
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    /// The login information for the user on the VCS.
    #[serde(rename = "login")]
    pub login: String,
    /// The name of the user.
    #[serde(rename = "name")]
    pub name: String,
}

impl User1 {
    /// The attribution actor who will run the scheduled pipeline.
    pub fn new(id: uuid::Uuid, login: String, name: String) -> User1 {
        User1 { id, login, name }
    }
}
