/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * The version of the OpenAPI document: v2
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Violation {
    #[serde(rename = "reason")]
    pub reason: String,
    #[serde(rename = "rule")]
    pub rule: String,
}

impl Violation {
    pub fn new(reason: String, rule: String) -> Violation {
        Violation { reason, rule }
    }
}
