/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * The version of the OpenAPI document: v2
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Webhook {
    /// URL to deliver the webhook to. Note: protocol must be included as well (only https is supported)
    #[serde(rename = "url")]
    pub url: String,
    /// Whether to enforce TLS certificate verification when delivering the webhook
    #[serde(rename = "verify-tls")]
    pub verify_tls: bool,
    /// The unique ID of the webhook
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    /// Masked value of the secret used to build an HMAC hash of the payload and passed as a header in the webhook request
    #[serde(rename = "signing-secret")]
    pub signing_secret: String,
    /// The date and time the webhook was last updated.
    #[serde(rename = "updated-at")]
    pub updated_at: String,
    /// Name of the webhook
    #[serde(rename = "name")]
    pub name: String,
    /// The date and time the webhook was created.
    #[serde(rename = "created-at")]
    pub created_at: String,
    #[serde(rename = "scope")]
    pub scope: Box<crate::models::WebhookScope>,
    /// Events that will trigger the webhook
    #[serde(rename = "events")]
    pub events: Vec<Events>,
}

impl Webhook {
    pub fn new(
        url: String,
        verify_tls: bool,
        id: uuid::Uuid,
        signing_secret: String,
        updated_at: String,
        name: String,
        created_at: String,
        scope: crate::models::WebhookScope,
        events: Vec<Events>,
    ) -> Webhook {
        Webhook {
            url,
            verify_tls,
            id,
            signing_secret,
            updated_at,
            name,
            created_at,
            scope: Box::new(scope),
            events,
        }
    }
}

/// Events that will trigger the webhook
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Events {
    #[serde(rename = "workflow-completed")]
    WorkflowCompleted,
    #[serde(rename = "job-completed")]
    JobCompleted,
}

impl Default for Events {
    fn default() -> Events {
        Self::WorkflowCompleted
    }
}
