/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * The version of the OpenAPI document: v2
 *
 * Generated by: https://openapi-generator.tech
 */

/// WebhookScope : The scope in which the relevant events that will trigger webhooks

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct WebhookScope {
    /// ID of the scope being used (at the moment, only project ID is supported)
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    /// Type of the scope being used
    #[serde(rename = "type")]
    pub r#type: String,
}

impl WebhookScope {
    /// The scope in which the relevant events that will trigger webhooks
    pub fn new(id: uuid::Uuid, r#type: String) -> WebhookScope {
        WebhookScope { id, r#type }
    }
}
